import React, { useState, useEffect } from "react";
import { Form, Button, Alert } from "react-bootstrap";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import Wrapper from './Wrapper';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const  Privacy = () => {
 
  
  return (
    <Wrapper >
      <Form >
    
          <p className="forgot-password text-right">
              <Link to={"/login"}>Go Back to Login page ... </Link>
          </p>
          
<h7 style='margin-top:.25in;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:21px;font-family:"Arial",sans-serif;font-weight:normal;margin:0in;text-align:center;'><strong><span style="font-size:45px;line-height:115%;color:#292929;">Data Privacy Policy</span></strong></h7>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">This Data Privacy Policy (also referred to as Policy or Privacy Notice) contains information on how KHPH Technologies Pte. Ltd. of Philippines (&ldquo;KraftHub&rdquo;) collects, uses, processes and discloses the User&rsquo;s Personal Data in connection with the access to and/or use of the online platforms of KraftHub including, but not limited to, the mobile application, website, and social media accounts (collectively the &ldquo;Sites&rdquo; or &ldquo;Site&rdquo;). &nbsp;It shall be the sole responsibility of the User to fully read and understand this Policy in accessing the Site or Sites and/or using the Site Services. The User shall be conclusively deemed to have agreed to this Policy and shall be deemed to have given consent to the collection, use, processing, and disclosure by KraftHub of Personal Data by a.) clicking &ldquo;Yes&rdquo; on the Policy pop-up or any web form referring to this Policy on any of the KraftHub Site or Sites, b.) submitting Personal Data to KraftHub when registering for a KraftHub Account, c.) accessing the KraftHub Site or Sites, or d.) using the KraftHub Site Services. &nbsp;If the User provides KraftHub Personal Data relating to a third party, the User shall be responsible for the required consent of the third party to provide KraftHub their Personal Data for the applicable purpose/s.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">1. DEFINITIONS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;KraftHub Account&rdquo; refers to the arrangement in which KraftHub grants the User the right to access and use the Site or Sites and Site Services upon compliance by the User of KraftHub requirements.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Personal Data&rdquo; means any data, whether true or not, which is (a) about an individual who can be identified (i) from that data; or (ii) from that data and other information to which we have or are likely to have access and would include data in our records as may be updated from time to time, or (b) defined as &ldquo;personal data&rdquo; or &ldquo;personal information&rdquo; under any applicable Data Protection Laws. Examples of Personal Data that KraftHub may collect include the User&rsquo;s name, contact details, email address, birthday, network and device data (including IP address and device or advertising identifiers).</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Site or Sites&rdquo; refers to the online platforms such as the mobile application, website, and social media accounts owned and maintained by KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Site Services&rdquo; refers to the hosting and maintenance of the Site or Sites by KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;User&rdquo; refers to any person or entity that accesses and/or uses the Site or Sites.&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">2. COLLECTION OF PERSONAL DATA</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">When accessing and/or using the Site or Sites, KraftHub may ask User to provide Personal Data which may include, but is not limited to, the User&rsquo;s name, birthday, physical address, email address, phone number. KraftHub may also collect information on how the Site or Sites are accessed and used (&quot;Usage Data&quot;). This Usage Data may include information such as the User&rsquo;s computer&apos;s Internet Protocol (IP) address, browser type, browser version, the areas of the Site or Sites that User visits, the time and date of the visit, the time spent on those Site areas, unique device identifiers and other similar data.&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub collects location data when the Site is running in the foreground (app open and on-screen) or background (app open but not on-screen) on the User&apos;s device. The location data is used to improve the User&apos;s experience on the Site by efficiently matching the User with nearby services.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub may use cookies and similar tracking technologies to track the activity on the Site or Sites. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to a User&rsquo;s browser from a website and stored on the User&rsquo;s device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze Site or Sites activity and performance.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">The User can instruct their browser to refuse all cookies or to indicate when a cookie is being sent. However, if the User do not accept cookies, such User may not be able to use some portions of the Site or Sites and Site Services.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub, on its own, does not usually collect the User&rsquo;s credit card details, which are collected, processed and stored directly by KraftHub&rsquo;s third-party payment processors pursuant to their terms of use and privacy policies. None of the User&rsquo;s credit card details are stored with KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3. &nbsp; USE OF PERSONAL DATA</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub may use and disclose Personal Data for purposes necessary to maintain the Site or Sites and provide the User the Site Services, including to: a.) register and maintain KraftHub Account, b.) deliver or perform the Site Services, c.) process and/or collect payment for KraftHub fees, KraftHub business partners fees, and other related fees and charges, d.) communicate with the User regarding queries, requests and feedback as well as material changes to the Site or Sites, Site Services, the Terms of Use, this Policy or other terms and conditions, e.) personalize and improve User experience in using the Site or Sites, f.) monitor and enforce compliance with the Terms of Use, including dispute resolution, g.) comply with internal risk controls, the terms of access to payment processing, financial or banking services such as credit card disputes, fraud, billing errors, or any applicable law h.) ensure KraftHub Site or Sites function properly and to improve their performance, by carrying out activities such as debugging and statistical analysis, i.) send User marketing communications in relation to KraftHub Site or Sites and in relation to the sales, products, services or promotions of business partners, j.) deliver ads which may be of interest to User on the Site or Sites or other websites, apps or online platforms, k.) invite User to KraftHub events, l.) process User participation in KraftHub and KraftHub business partners&rsquo; promotions and initiatives, m.) conduct market and customer research, analysis or tracking, n.) manage the administrative and business operations of KraftHub, and o.) for other purposes which are reasonably related to the foregoing.&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub will make reasonable efforts to ensure that the Personal Data it will use or disclose to another organization is accurate and complete. However, the User must update KraftHub of any changes in the Personal Data. KraftHub will not be responsible for relying on inaccurate or incomplete Personal Data if User have not updated KraftHub of changes.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">4. STORAGE, RETENTION, AND SECURITY OF PERSONAL DATA</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">The Personal Data is stored and processed in Philippines. If the User is located outside the Philippines and chooses to provide Personal Data to KraftHub, the User is informed that Personal Information is stored and processed on computers located outside of the User&rsquo;s state, province, country or other governmental jurisdiction where the data protection laws may differ from those of the User&rsquo;s jurisdiction.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub will not retain Personal Data for longer than necessary and will take reasonable steps to destroy or permanently de-identify Personal Data. &nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub will take all the steps reasonably necessary to ensure that Personal Data is treated securely and in accordance with this Privacy Policy and no transfer of Personal Data will take place to an organization or a country unless there are adequate controls in place. &nbsp;In the event that KraftHub becomes aware of a security breach which KraftHub may believe has resulted or may result in the unauthorized access, use, or disclosure of Personal Data, KraftHub will promptly investigate the matter and notify the User of such breach. &nbsp;However, KraftHub will not be responsible for any unauthorized use of Personal Data by third parties which is attributable to factors beyond the control of KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5. SHARING AND DISCLOSURE OF PERSONAL DATA</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Pursuant to the stated uses of Personal Data, KraftHub may disclose User&rsquo;s Personal Data to:</span></p>
<ol style="list-style-type: decimal;margin-left:30px;">
    <li><span style="line-height:115%;font-size:15px;">Employees, consultants, and other personnel;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Other User of the Site or Sites;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Payment processors, who process User&rsquo;s payment on the Site or Sites;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Logistics providers, such as courier services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Business partners in connection with the processing of any promotion, event or service organized by KraftHub;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Professional advisers and consultants;</span></li>
    <li><span style="line-height:115%;font-size:15px;">Agents, contractors or service providers who provide operational services to us, such as online cloud storage and processing, marketing optimization, information technology, telecommunications, security or other relevant services which requires their collection, use or disclosure of Personal Data; and</span></li>
    <li><span style="line-height:115%;font-size:15px;">Any other party whom a User authorizes us to disclose Personal Data to.</span></li>
</ol>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Under certain circumstances, KraftHub may be required to disclose Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency). KraftHub may disclose Personal Data in the good faith belief that such action is necessary to:</span></p>
<ol style="list-style-type: decimal;margin-left:30px;">
    <li><span style="line-height:115%;font-size:15px;">To comply with a legal obligation;</span></li>
    <li><span style="line-height:115%;font-size:15px;">To protect and defend the rights or property of KraftHub;</span></li>
    <li><span style="line-height:115%;font-size:15px;">To prevent or investigate possible wrongdoing in connection with the use of the Site or Sites;</span></li>
    <li><span style="line-height:115%;font-size:15px;">To protect the personal safety of User of the Site or Sites or the public; and</span></li>
    <li><span style="line-height:115%;font-size:15px;">To protect against legal liability.&nbsp;</span></li>
</ol>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">6. ACCESS TO AND CORRECTION OF PERSONAL DATA</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">User may access or correct their names, birthdays, and addresses by logging in the KraftHub Account on the Site or Sites and clicking the &ldquo;Edit&rdquo; button under each relevant field.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">For Personal Data that cannot be corrected by User by logging in to their KraftHub Account on the Site or Sites, the User may request access to and correct such Personal Data by emailing our Data Protection Officer at <span style="color:#0C87FA;">mykelrase@gmail.com</span>.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub may need to request additional information from the User to confirm User&rsquo;s identity before providing the access or making the correction.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub will do its best to respond to Personal Data access and correction requests within 30 days. Where KraftHub is unable to meet this timeline, KraftHub update the User with the soonest possible time within which it can provide the information or make the correction. It must be noted that certain types of Personal Data access and correction requests may be exempt under Applicable Laws.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">It must also be noted that KraftHub may charge a User a reasonable fee for the handling and processing of their Personal Data access request.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub will promptly send the corrected Personal Data to every other person or entity to which such Personal Data was disclosed by KraftHub within the year before the date of the correction, unless such person or entity does not need the corrected Personal Data for any legal or business purpose.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Subject to obtaining User&rsquo;s consent, KraftHub may send the corrected Personal Data only to specific organizations to which the Personal Data was disclosed by KraftHub within a year before the date the correction was made.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">7. WITHDRAWAL OF CONSENT</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">User may withdraw consent for the collection, use and/or disclosure of any Personal Data by KraftHub by submitting a written request through email to our Data Protection Officer via <span style="color:#0C87FA;">mykelrase@gmail.com</span>.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Note that, depending on the nature of the consent withdrawal, KraftHub may not be able to continue to allow User access to the Site or Sites and/or use of Site Services. KraftHub will process such a request within a reasonable time from receiving notice from User of the withdrawal of consent. Once the processing is complete, KraftHub will no longer collect, use and/or disclose Personal Data, except to the extent KraftHub needs to retain Personal Data for compliance, regulatory or other legal purposes.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">User may withdraw consent for KraftHub to send sales, marketing or promotional information by clicking on the Unsubscribe link in the promotional emails sending an email at the email address provided below.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Once KraftHub receives a notification that User wishes to withdraw consent for receiving marketing or promotional materials or communications, it may take up to thirty (30) days for the withdrawal to be reflected in KraftHub systems. Therefore, the User may still receive marketing or promotional materials or communications during this period.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">8. CONTACTING KraftHub</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">For any questions relating to Personal Data or about this Policy, or if a User has a complaint regarding the collection, use or handling of Personal Data by KraftHub, a User may contact our Data Protection Officer via one of the following methods:</span></p>
<ol style="list-style-type: decimal;margin-left:30px;">
    <li><span style="line-height:115%;font-size:15px;">Email address: mykelrase@gmail.com</span></li>
    <li><span style="line-height:115%;font-size:15px;">Office address: STI Academic Center, University Parkway Drive, Taguig, Metro Manila</span></li>
</ol>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">9. DATA POLICY UPDATES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub may update this Policy to ensure that it is consistent with industry trends and/or any changes in legal or regulatory requirements. The User agrees to be bound by the prevailing terms of the Policy as updated from time to time.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">10. GOVERNING LAW</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">This Policy and use of the Site or Sites and/or Site Services shall be governed in all respects by the laws of the Philippines.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:16px;line-height:115%;">&nbsp;</span></p>
         <ToastContainer />
        </Form>
    </Wrapper>
  );
}

export default Privacy;
