import React, { useState, useEffect } from "react";
import { Form, Button, Alert } from "react-bootstrap";
import { Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import Wrapper from './Wrapper';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const  Terms = () => {
 
  
  return (
    <Wrapper >
      <Form >
    
          <p className="forgot-password text-right">
              <Link to={"/login"}>Go Back to Login page ... </Link>
          </p>
<h2 style='margin-top:.25in;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;line-height:115%;font-size:21px;font-family:"Arial",sans-serif;font-weight:normal;margin:0in;text-align:center;'><strong><span style="font-size:45px;line-height:115%;color:#292929;">Terms of Use</span></strong></h2>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">These Terms of Use shall govern the access to and/or use of the online platforms of MKPH Technologies Pte. Ltd. of the Philippines (&ldquo;KraftHub&rdquo;) including, but not limited to, the mobile application, website, and social media accounts (collectively the &ldquo;Sites&rdquo; or &ldquo;Site&rdquo;). It shall be the sole responsibility of the User to fully read and understand these Terms of Use in accessing the Site or Sites and/or using the Site Services. Access of the Site or Sites and/or use of the Site Services shall constitute acceptance of, and agreement to be bound by these Terms of Use. If you do not agree to these Terms of Use, do not access and/or use the Site or Sites.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">1. DEFINITIONS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 1 states the meaning of the following words and phrases used in these Terms of Use.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Site or Sites&rdquo; refers to the mobile application, website, and social media accounts owned and maintained by KraftHub, which are online platforms where Clients and KraftHub Partners can identify and connect with each other for the purpose of executing an agreement on performance of various services required by Client.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Site Services&rdquo; refers to the hosting and maintenance of the Site or Sites by KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;User&rdquo; refers to any person or entity that accesses and/or uses the Site or Sites whether as a visitor, a Client or as a KraftHub Partner.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;KraftHub Account&rdquo; refers to the arrangement in which KraftHub grants the User the right to access and use the Site or Sites and Site Services upon compliance by the User of the KraftHub requirements.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Client&rdquo; refers to any person or entity that requires the performance of certain services which are offered by a KraftHub Partner.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;KraftHub Partner&rdquo; refers to any person or entity that offers the performance of services through the Site or Sites.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Project&rdquo; refers to an engagement for KraftHub Partner services that a KraftHub Partner provides to a Client as a result of the use of the Site or Sites.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Service Contract&rdquo; refers to the agreement between a Client and a KraftHub Partner governing the services to be performed by a KraftHub Partner for Client for a Project.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Payment Method&rdquo; refers to a valid credit card issued by a bank acceptable to KraftHub, or such other method of payment as KraftHub may accept from time to time in its sole discretion.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">2. PURPOSE OF KRAFTHUB</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Section 2 discusses what KraftHub does and does not do when allowing use of the Site and providing the Site Services.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">2.1 KRAFTHUB BUSINESS ACTIVITY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub is a technology company that owns and maintains the Site or Sites and makes the Site and Site Services available to Users to enable KraftHub Partners and Clients to find and transact directly with each other. Through the Site and Site Services, KraftHub Partners may be notified of Clients seeking the services they offer, and Clients may be notified of KraftHub Partners that may offer the services they seek.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">2.2 KraftHub LIMITATIONS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) KraftHub does not introduce KraftHub Partners to Clients, find Projects for KraftHub Partners, or find KraftHub Partners for Clients. If Users decide to enter into a Service Contract, the Service Contract is directly between the Users, and KraftHub is not a party to that Service Contract.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) KraftHub does not: (i) make any representations for or guarantee the truth or accuracy of any KraftHub Partner&rsquo;s or Client&rsquo;s information and contents on the Site; (ii) does not verify any feedback or information provided by Users about KraftHub Partners or Clients; and (iii) does not vet or otherwise perform background checks on KraftHub Partners or Clients.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) KraftHub does not, in any way, supervise, direct, control, or evaluate KraftHub Partners or their work and is not responsible for any Project, Project terms or work products.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(d) KraftHub makes no representations for and does not guarantee, and Users agree not to hold KraftHub responsible for the quality, safety, or legality of KraftHub Partner services; the qualifications, backgrounds, or identities of Users; the ability of KraftHub Partners to deliver KraftHub Partner services; the ability of Clients to pay for KraftHub Partner services; User information and content, statements or posts made by Users; or the ability or willingness of a Client or KraftHub Partner to actually complete a transaction.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(e) KraftHub will not have any liability or obligations under or related to Service Contracts and/or KraftHub Partner services for any acts or omissions by the Users.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(f) KraftHub does not, in any way, supervise, direct, or control any KraftHub Partners or KraftHub Partner services; does not impose quality standards or a deadline for completion of any KraftHub Partner services; and does not dictate the performance, methods or processes any KraftHub Partner uses to perform services.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(g) KraftHub does not, in any way, provide or guarantee the KraftHub Partner a regular salary or any minimum or regular payment. A KraftHub Partner will be paid by a Client at such times and amounts as agreed upon with such Client in a given Service Contract. Consequently, KraftHub shall not be responsible as a withholding agent for any withholding taxes on the payments pursuant to a Service Contract.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(h) KraftHub does not provide KraftHub Partners with training or any equipment, labor, tools, or materials related to any Service Contract.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(i) KraftHub does not provide the premises at which KraftHub Partners will perform the work. It shall be the sole discretion of KraftHub Partners whether or not to engage with subcontractors or employees to perform KraftHub Partner services. Whether or not any KraftHub Partner uses subcontractors or employees, the KraftHub Partner further agrees and acknowledges that it is solely responsible for acts or omissions of its subcontractors or employees with respect to the Project.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">3. KRAFTHUB ACCOUNTS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 3 states the requirements and consequences of creation of a KraftHub Account.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.1 REGISTRATION AND ACCEPTANCE</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">To access and use certain portions of the Site or Sites and Site Services, a User must register for a KraftHub Account. By registering for a KraftHub Account and by accepting the Terms of Use when prompted on the Site or Sites, a User agrees to be bound and to abide by the provisions of these Terms of Use and subsequent changes.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub reserves the right to decline a registration for a KraftHub Account or to add to an Account or Accounts of a User.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Certain portions of the Site or Sites are available to Site visitors, including those portions before an Account registration is accepted. These Terms of Use shall be applicable with respect to access of such portions by Site visitors.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.2 ACCOUNT ELIGIBILITY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub offers the Site and Site Services for lawful business and individual needs of the User. With the registration of a KraftHub Account and use of the Site and Site Services, it is represented and warranted that the User:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) will use the Site and Site Services for valid business and individual purposes only;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) has the capacity to enter into contracts and is of majority age, if the User is an individual who registers a KraftHub Account in their personal capacity;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) is duly authorized to enter into binding contracts, including these Terms of Use, and to create and register a KraftHub Account on behalf of a company, if the User is an employee, officer, agent, or representative of a company;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(d) has a valid and duly registered business, if the User is a self-employed individual/sole proprietor, corporation, limited liability company, or other juridical entity;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(e) is compliant with any registration, licensing, permit, or other requirements with respect to the conduct of business, if the User is engaged in business.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.3 ACCOUNT PROFILE</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">To register for a KraftHub Account to join the Site, a User must complete a User profile (&ldquo;Profile&rdquo;), which the User consents to be shown to other Users and, unless the User changes the privacy settings, the public. The User agrees to provide true, accurate, and complete information in the Profile, in all registration and other forms on the Site or Sites completed by the User, or in other documents that the User provides to KraftHub. In addition, the User shall be responsible in updating their own information in the Site or Sites. The User agrees not to provide any inaccurate, false or misleading information in the Site or Sites and the User shall rectify or correct any information that is or becomes false or misleading.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.4 KRAFTHUB ACCOUNT TYPES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">The two (2) types of KraftHub Accounts are the Client Account and the KraftHub Partner Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">3.4.1 CLIENT ACCOUNT</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">If the User desires to avail of the services of any of the KraftHub Partners, the User can register for a Client Account or add a Client Account to an existing KraftHub Partner Account. A Client Account may have several authorized Users and each User under a Client Account (&ldquo;Client Team Member&rdquo;) can be given different permissions to act on behalf of the Client Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">3.4.2 KRAFTHUB SERVICE PROVIDER ACCOUNT</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">A User who offers skills and services required by Clients in the Site or Sites can register for a KraftHub Partner Account or add a KraftHub Partner Account to an existing Client Account. A KraftHub Partner Account may have several authorized Users and each User under a KraftHub Partner Account (&ldquo;KraftHub Partner Team Member&rdquo;) can be given different permissions to act on behalf of the KraftHub Partner Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.5 ACCOUNT PERMISSIONS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">By granting Client Team or KraftHub Partner Team Member/s permissions under a Client or KraftHub Partner Account, a User represents and warrants that:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) the Client/KraftHub Partner Team Member is authorized to act on behalf of the User;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) they are financially responsible for the Client/KraftHub Partner Team Member&rsquo;s actions taken in accordance with those permissions, including, if applicable, entering into binding contracts on behalf of the User; and,</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) they are fully responsible and liable for any action of a Client/KraftHub Partner Team Member, including making payments and entering into Service Contracts.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.6 IDENTITY AND LOCATION VERIFICATION</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">From time to time, a registered KraftHub Account will be subject to verification, including, but not limited to, validation against third-party databases or official government or other legal documents that confirm the User&rsquo;s identity, location, and other relevant matters. Subject to the existing law and regulations on data privacy, by registering a KraftHub Account, a User authorizes KraftHub, directly or through third parties, to require submission of documents and information and make inquiries necessary to validate a User&rsquo;s identity, location, ownership of e-mail address and credit card accounts registered with KraftHub, and other related matters. When requested by KraftHub, a User must provide timely and complete information necessary for the verification and validation of the User&rsquo;s KraftHub Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.7 USERNAMES AND PASSWORDS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">When a User registers for a KraftHub Account, the User will be asked to identify a username and password for the KraftHub Account. The User is entirely responsible for safeguarding and maintaining the confidentiality of the username and password and agrees not to share such username and password with any person who is not authorized to use the Account. The User authorizes KraftHub to assume that any person using the Site or Sites with the User&rsquo;s username and password has been duly authorized by the User. The User agrees to notify KraftHub immediately if it is suspected or it becomes known by the User that there has been unauthorized access of Account or any unauthorized use of the username and/or password for the User&rsquo;s KraftHub Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3.8 REVOCATION AND CLOSURE OF ACCOUNT</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub reserves the right, in its sole discretion, to revoke the registration of an Account/s without prior notice to the affected User if such User violates the Terms of Use and upon finding that misleading information has been provided in creating, marketing, or maintaining the Profile or Account.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">4. RESPONSIBILITIES OF USERS, CLIENTS, AND KRAFTHUB SERVICE PROVIDERS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 4 discusses some of the responsibilities of Users when using the Site and Site Service to find, evaluate, and enter into a Service Contract with a KraftHub Partner or Client.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">4.1 RESPONSIBILITIES OF USERS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">At all times, Users are solely responsible for evaluating and determining the suitability of any Project, Client or KraftHub Partner. Users acknowledge, agree, and understand that KraftHub is not a party to the relationship or any dealings between Client and KraftHub Partner. Without limitation, Users are solely responsible for:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) ensuring the accuracy and legality of any User information and content;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) determining the suitability of other Users for a Service Contract through the conduct of interviews, vetting, background checks, or other similar actions;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) assessing whether or not to enter into a Service Contract with another User and for verifying any information about another User, feedback, comments, ratings and other relevant information from other Users</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(d) negotiating, agreeing to, and executing any terms or conditions of Service Contracts.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">4.1.1 RESPONSIBILITIES OF CLIENTS</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">Users who are Clients shall additionally be responsible for:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(a) ensuring that services required to be rendered by KraftHub Partners are possible and legal;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(b) paying for services rendered by KraftHub Partners and withholding and remitting to the appropriate government agency any taxes and/or mandatory contributions, if applicable;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(c) obtaining the appropriate government registration and permits, in the case of Clients engaged in business and who require KraftHub Partners services in relation with their business.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">4.1.2 RESPONSIBILITIES OF KRAFTHUB SERVICE PROVIDERS</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">KraftHub Partners acknowledge and agree to be solely responsible for:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(a) performing the services required by Clients in accordance with the agreement entered into with Client;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(b) invoicing and tax reporting and payment associated with payments received from Clients, without any obligation to withhold any taxes on the part of KraftHub;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(c) obtaining the appropriate government registration and permits in relation with the performance of services;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(d) paying the compensation or service fees of employees and subcontractors, respectively, engaging to perform the services required by Clients and remitting to the appropriate government agency the corresponding withholding taxes and/or mandatory contributions;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><span style="font-size:15px;line-height:115%;">(e) securing insurance covering liability, health, workers&rsquo; compensation, disability, unemployment, or other insurance needed, desired, or required by law.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-left:30.0pt;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Nothing in these Terms of Use is intended to prohibit or discourage, nor should be construed as prohibiting or discouraging, any KraftHub Partner from engaging in any other business activities or providing any services through any other channels they choose.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">In the event of an audit of KraftHub, the KraftHub Partner agrees to promptly cooperate with KraftHub and provide copies of KraftHub Partner&rsquo;s tax returns and other documents as may be reasonably requested for purposes of such audit, including, but not limited to, records showing KraftHub Partner is engaging in an independent business as represented by KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">4.2. MARKETPLACE FEEDBACK AND USER CONTENT</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users hereby allow KraftHub to publish on the Site or Sites, on their behalf and solely for the convenience of Users, information about the User, such as User identity, User credentials, feedback, ratings, and comments of other Users, geographical location, among other things. However, such information is based solely on unverified data that KraftHub Partners or Clients voluntarily submit to KraftHub and does not constitute and will not be construed as an introduction, endorsement, or recommendation by KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users acknowledge and agree that User feedback benefits the marketplace, all Users, and the efficiency of the Site, and the User specifically requests that KraftHub post composite or compiled feedback about Users, including themselves on User Profiles and elsewhere on the Site or Sites. Users acknowledge and agree that feedback results for Users, including Users Client Satisfaction Score, wherever referenced, and other User Content highlighted by KraftHub on the Site or otherwise &ldquo;Composite Information&rdquo;, if any, will include User comments, User ratings, indicators of User satisfaction, and other feedback left exclusively by other Users. Users further acknowledge and agree that KraftHub will make Composite Information available to other Users, including composite or compiled feedback. KraftHub provides its feedback system as a means through which Users can share their opinions of other Users publicly, and KraftHub does not monitor, influence, contribute to or censor these opinions. Users acknowledge and agree that posted composite or compiled feedback and any other Composite Information relates only to the business advertised in the Profile and not to any individual person. Users agree not to use the Composite Information to make any employment, credit, credit valuation, underwriting, or other similar decision about any other User.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub does not generally investigate any remarks posted by Users or other User Content for accuracy or reliability and does not guarantee that User Content is accurate. Users are solely responsible for their respective User Content, including the accuracy of any User Content, and are solely responsible for any legal action that may be instituted by other Users or third parties as a result of or in connection with User Content if such User Content is legally actionable or defamatory. KraftHub is not legally responsible for any feedback or comments posted or made available on the Site or Sites by any Users or third parties, even if that information is defamatory or otherwise legally actionable. In order to protect the integrity of the feedback system and protect Users from abuse, KraftHub reserves the right, but is under no obligation, to remove posted feedback or information that, in KraftHub&rsquo;s sole judgment, violates the Terms of Use or negatively affects our marketplace, diminishes the integrity of the feedback system or otherwise is inconsistent with the business interests of KraftHub. Users acknowledge and agree that Users will notify KraftHub of any error or inaccurate statement in the feedback results, including the Composite Information, and that if Users do not do so, KraftHub may rely on the accuracy of such information.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">5. KRAFTHUB FEES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 5 describes what fees Users agree to pay to KraftHub in exchange for KraftHub allowing the use of the Site and Site Services.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.1 KRAFTHUB SERVICE PROVIDERS PAYMENTS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub Partners pay KraftHub fees (&ldquo;KraftHub Fees&rdquo;) for using the Site&rsquo;s or Sites&rsquo; communication, charging, reporting, dispute resolution and payment features. When a Client pays a KraftHub Partner for services and/or other expenses pertaining to a Project, KraftHub will credit the KraftHub Partner&rsquo;s Account for the full amount paid by Client, and then deducts and disburses to KraftHub the corresponding KraftHub Fees. The KraftHub Partner hereby irrevocably authorizes and instructs KraftHub to deduct the KraftHub Fees from the KraftHub Partner Account and disburse the said KraftHub fees to KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.2 ADMINISTRATION FEES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub Partners may pay KraftHub an administration fee (&ldquo;Administration Fee&rdquo;) to cover costs for the maintenance of the Site or Sites and administration of payments via the disbursement method chosen by KraftHub Partner. The Administration Fee corresponding to each disbursement method is listed under Fees and Schedules on the Site and is subject to revision as and when KraftHub may deem necessary.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.3 PAYMENT PROCESSING AND ADMINISTRATION FEES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Clients pay KraftHub fees for payment processing and administration related to the KraftHub Partner Fees that Clients may pay to KraftHub Partners pursuant to a Service Contract between the Client and KraftHub Partner.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.4 GOVERNMENT CHARGES</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub may be required by applicable law to collect and remit government charges such as, but not limited to, taxes and mandatory insurance premium contributions from KraftHub Partners and/ or Clients. In such instances, any amount KraftHub is required to collect and/or withhold and remit to the government shall be in addition to, and shall not be considered as part of the fees owed to KraftHub under these Terms of Use.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.5 NO FEE FOR INTRODUCING OR FOR FINDING PROJECTS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub does not introduce Clients to KraftHub Partners and does not help KraftHub Partners secure Projects. KraftHub merely makes the Site and Site Services available to enable KraftHub Partners to connect with Users. Therefore, KraftHub does not charge a fee when a KraftHub Partner finds a suitable Client or finds a Project. In addition, KraftHub does not charge any fee or dues for posting User ratings and feedback, including Composite Information.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5.6 PAYMENT METHODS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Payment of the KraftHub Fees and/or Administration Fees shall be through a valid Payment Method such as a credit card, or any other Payment Method which may be acceptable to KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">In case of payment through credit card, Users must provide the necessary credit card account and shall authorize KraftHub to:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) run the necessary credit card authorizations;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) store credit card, bank, or other relevant financial information of the User, subject to the provisions of the KraftHub Privacy Policy;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) charge User&rsquo;s credit card (or any other Payment Method) for the KraftHub Fees and any other amounts owed under the Terms of Use. To the extent permitted by applicable law and subject to our Privacy Policy, Users acknowledge and agree that KraftHub may use certain third-party vendors and service providers to process payments and manage the User&rsquo;s Payment Method information.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">By providing Payment Method information through the Site or Sites and authorizing payments through the chosen Payment Method, the User represents, warrants, and covenants that:</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(a) User is legally authorized to provide such information;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(b) User is legally authorized to make payments using the chosen Payment Method;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(c) the Client Team Member or KraftHub Partner Team Member providing Payment Method Information and authorizing payments is an employee, agent, or representative of the User who is duly authorized by the company or person to undertake said actions;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">(d) the foregoing actions do not violate the terms and conditions applicable to the User&rsquo;s use of such Payment Method or applicable law.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">When the User authorizes payments using a Payment Method via the Site or Sites, the User represents and warrants that there are sufficient funds or credit available to complete the payment using the designated Payment Method. To the extent that any amounts owed under these Terms of Use or the other supplementary agreements and arrangements cannot be collected from User&rsquo;s nominated Payment Method, User is solely and immediately responsible for payment of such amounts by other lawful means.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Because the use of any Payment Method may be limited by applicable law or by written agreement with the User&rsquo;s financial institution, KraftHub is not liable to any User if KraftHub does not complete a transaction as a result of such limitation or if the applicable financial institution fails to honor any credit or debit to or from an account associated with such Payment Method.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">6. NON-BYPASS OF KRAFTHUB</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 6 discusses a User&rsquo;s agreement to engage with a Client or KraftHub Partner only through KraftHub for two years from the date of connection with such Client or KraftHub Partner through the Site or Sites.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">6.1 ACTS OF BYPASS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users acknowledge and agree that for twenty-four (24) months from the time a User connects with another User through the Site or Sites (&ldquo;Non-Bypass Period&rdquo;), Users shall use the Site or Sites as the exclusive channel to request for and/or offer work or services and pay for and/or receive all payments for work or services with such other User. During the Non-Bypass Period, the affected Users may not directly transact with each other or may not transact through other channels or intermediaries other than KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users agree that the following are instances of, but not limited to, violation of the non-Bypass provision of these Terms of Use:</span></p>
<ul style="list-style-type: undefined;margin-left:30px;">
    <li><span style="line-height:115%;font-size:15px;">Submission through means other than the Site or Sites of proposals to, or solicitation from other Users who were identified by the proposing or soliciting User through the Site or Sites.</span></li>
    <li><span style="line-height:115%;font-size:15px;">Acceptance of proposals or solicitations through means other than the Site or Sites by Users who were identified by the proposing or soliciting User through the Site or Sites.</span></li>
    <li><span style="line-height:115%;font-size:15px;">Execution of contracts, invoicing, or receipt of payments outside the Site or Sites by Users who were previously connected through the Site.</span></li>
    <li><span style="line-height:115%;font-size:15px;">Declaration of, and/or invoicing on the Site for payment in an amount lower than that agreed between Users.</span></li>
    <li><span style="line-height:115%;font-size:15px;">Referral of a User identified by the referring User on the Site to a third party who is not a User of the Site for purposes of making or receiving payments outside the Site or Sites.</span></li>
</ul>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">6.2 PENALTY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users who commit acts of bypass agree to be liable to KraftHub for liquidated damages in the amount of PhP1,000,000.00.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users agree to notify KraftHub immediately if another User suggests the commission of the foregoing acts of bypass or other similar acts.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">7. CONTRACTUAL RELATIONSHIP BETWEEN CLIENT AND KRAFTHUB SERVICE PROVIDER</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 7 discusses the nature of the relationship between a Client and a KraftHub Partner.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">7.1 SERVICE CONTRACT BETWEEN CLIENT AND KRAFTHUB SERVICE PROVIDER</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">If a Client and a KraftHub Partner connect through the Site or Sites and enter into a Service Contract with respect to a Project, such Service Contract pertains to a contractual relationship directly and exclusively between the Client and KraftHub Partner. Users acknowledge and agree that KraftHub is not a party to such Service Contracts, and that the execution of a Service Contract between Users will not, under any circumstance, create an employment, partnership or joint venture, or other service relationship between KraftHub and the Users.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">With respect to any Service Contract, Clients and KraftHub Partners may enter into any written agreements that they deem appropriate (e.g., confidentiality agreements, invention assignment agreements, assignment of rights, etc.) provided that any such agreements do not conflict with, limit, or expand KraftHub&rsquo;s rights and obligations under the Terms of Use.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">7.2 DISPUTES AMONG USERS</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">For disputes arising between Clients and KraftHub Partners connected to the access and use of the Site or Sites, Users agree to abide by the dispute process provided in these Terms of Use that apply to the Users&rsquo; particular Service Contract. If the dispute process does not resolve the dispute between the Users, the latter may pursue other dispute resolution measures independently, but Users acknowledge and agree that KraftHub will not and is not obligated to provide any dispute assistance.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users hereby release KraftHub, its subsidiaries, affiliates, officers, directors, agents, partners, employees, and service providers from claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with any dispute you have with another User. This release includes, but is not limited to, disputes regarding the performance and quality of KraftHub Partner Services provided to a Client by a KraftHub Partner and non-payment by a Client for KraftHub Partner Services rendered.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">8. TRADEMARKS AND INTELLECTUAL PROPERTY RIGHTS</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 9 discusses the intellectual property rights of KraftHub.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">8.1 The KraftHub names and logos and all related names, design marks, and slogans are the trademarks or service marks of KraftHub.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">8.2 KraftHub is the owner of all the materials: illustrations, photographs, video or audio sequences, or any graphics published on the Site or Sites. Those works are protected by copyright laws and treaties around the world. All such rights are reserved and may not be used without KraftHub&rsquo;s expressed approval in writing.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">8.3 KraftHub must not use any part of the materials on the Site or Sites for commercial purposes without obtaining a license to do so from us or from our licensors. Reproduction or use of said materials in any format, digital or otherwise, for purposes of promotion, publication, display, or distribution beyond the scope of these Terms of Use is prohibited without a written permission from KraftHub. Unauthorized use of the Site or Sites may give rise to a claim for damages and/or be a criminal offense.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">9. WARRANTY AND LIMITATION OF LIABILITY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 10 discusses KraftHub warranty and liability limitations to Users.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">9.1 KRAFTHUB WARRANTY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">THE SITE AND THE SITE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. KRAFTHUB MAKES NO REPRESENTATIONS OR WARRANTIES WITH REGARD TO THE SITE, THE SITE SERVICES, WORK PRODUCT, OR ANY ACTIVITIES OR ITEMS RELATED TO THIS TERMS OF USE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KRAFTHUB DISCLAIMS ALL EXPRESS AND IMPLIED CONDITIONS, REPRESENTATIONS, AND WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF ACCURACY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. SOME JURISDICTIONS MAY NOT ALLOW FOR ALL OF THE FOREGOING LIMITATIONS ON WARRANTIES, SO TO THAT EXTENT, SOME OR ALL OF THE ABOVE LIMITATIONS MAY NOT APPLY TO THE USER. SECTION 14 (TERM AND TERMINATION) STATES USER&rsquo;S SOLE AND EXCLUSIVE REMEDY AGAINST KRAFTHUB WITH RESPECT TO ANY DEFECTS, NONCONFORMANCES, OR DISSATISFACTION. YOU AGREE NOT TO RELY ON THE SITE, THE SITE SERVICES, ANY INFORMATION ON THE SITE, OR THE CONTINUATION OF THE SITE.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">9.2 LIMITATION OF LIABILITY OF KRAFTHUB</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub is not liable, and you agree not to hold us responsible, for any damages or losses arising out of or in connection with the Terms of Use, including, but not limited to:</span></p>
<ul style="list-style-type: undefined;margin-left:30px;">
    <li><span style="line-height:115%;font-size:15px;">your use of or your inability to use KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">delays or disruptions in KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">viruses or other malicious software obtained by accessing, or linking to KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">glitches, bugs, errors, or inaccuracies of any kind in KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">damage to your hardware or device from the use of the KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">the content, actions, or inactions of third parties&rsquo; use of the KraftHub Site or Sites or Site Services;</span></li>
    <li><span style="line-height:115%;font-size:15px;">a suspension or other action is taken with respect to the User&rsquo;s Account;</span></li>
    <li><span style="line-height:115%;font-size:15px;">User&rsquo;s reliance on the quality, accuracy, or reliability of job postings, Profiles, ratings, recommendations, and feedback (including their content, order, and display), Composite Information, or metrics found on, used on, or made available through the KraftHub Site or Sites; and</span></li>
    <li><span style="line-height:115%;font-size:15px;">The User&rsquo;s need to modify practices, content, or behavior or User&rsquo;s loss of or inability to do business, as a result of changes to the Terms of Use.</span></li>
</ul>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">ADDITIONALLY, IN NO EVENT WILL KRAFTHUB, OUR AFFILIATES, OUR LICENSORS, OR OUR THIRD-PARTY SERVICE PROVIDERS BE LIABLE FOR ANY SPECIAL, CONSEQUENTIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, OR INDIRECT COSTS OR DAMAGES, INCLUDING, BUT NOT LIMITED TO, LITIGATION COSTS, INSTALLATION AND REMOVAL COSTS, OR LOSS OF DATA, PRODUCTION, PROFIT, OR BUSINESS OPPORTUNITIES. THE LIABILITY OF KRAFTHUB, OUR AFFILIATES, OUR LICENSORS, AND OUR THIRD-PARTY SERVICE PROVIDERS TO ANY USER FOR ANY CLAIM ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT OR THE OTHER TERMS OF SERVICE WILL NOT EXCEED THE LESSER OF: (A) $1.00 OR (B) ANY FEES RETAINED BY KRAFTHUB WITH RESPECT TO SERVICE CONTRACTS ON WHICH USER WAS INVOLVED AS CLIENT OR KRAFTHUB SERVICE PROVIDER DURING THE SIX-MONTH PERIOD PRECEDING THE DATE OF THE CLAIM. THESE LIMITATIONS WILL APPLY TO ANY LIABILITY, ARISING FROM ANY CAUSE OF ACTION WHATSOEVER ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT OR THE OTHER TERMS OF SERVICE, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH COSTS OR DAMAGES AND EVEN IF THE LIMITED REMEDIES PROVIDED HEREIN FAIL OF THEIR ESSENTIAL PURPOSE.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">10. INDEMNIFICATION</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 9 discusses the User&rsquo;s agreement to pay for any costs or losses KraftHub may incur as a result of a claim brought against KraftHub related to the User&rsquo;s use of the Site or Site or Site Services.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users will indemnify, defend, and hold harmless KraftHub, its affiliates, directors, officers, employees, representatives, and agents (each an &ldquo;Indemnified Party&rdquo;) for all Indemnified Claims (defined below) and Indemnified Liabilities (defined below) relating to or arising out of: (a) the use of the Site or Sites and the Site Services by Users or User&rsquo;s agents, including any payment obligations or default incurred through use of the Site Services; (b) any Service Contract entered into by Users who have connected with each other through the Site or Sites; (c) any employment-related claims between Users and their employees, such as those relating to employment termination, employment discrimination, harassment, or retaliation; and any claims for unpaid wages or other compensation, overtime pay, sick leave, holiday or vacation pay, retirement benefits, worker&rsquo;s compensation benefits, unemployment benefits, or any other employee benefits; (d) failure to comply with the Terms of Use by Users or their agents; (d) failure to comply with applicable law by Users or their agents; (e) negligence, willful misconduct, or fraud by Users or their agents; and (f) defamation, libel, violation of privacy rights, unfair competition, or infringement of Intellectual Property Rights or allegations thereof to the extent caused by Users or their agents. For purposes of this Section 9, User&rsquo;s agents include any person who has apparent authority to access or use a User&rsquo;s account demonstrated by using the User&rsquo;s username and password.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Indemnified Claim&rdquo; means any and all claims, damages, liabilities, costs, losses, and expenses (including reasonable attorneys&rsquo; fees and all related costs and expenses) arising from or relating to any claim, suit, proceeding, demand, or action brought by User or a third party or other User against an Indemnified Party.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&ldquo;Indemnified Liability&rdquo; means any and all claims, damages, liabilities, costs, losses, and expenses (including reasonable attorneys&rsquo; fees and all related costs and expenses) arising from or relating to any claim, suit, proceeding, demand, or action brought by an Indemnified Party against User or a third party or other User.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">11. AGREEMENT TERM AND TERMINATION</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 13 discusses User&rsquo;s and KraftHub&rsquo;s agreement about when and how long these Terms of Use will last, and when and how either User or KraftHub can end the binding effect of these Terms of Use.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">11.1 TERMINATION</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Unless both User and KraftHub expressly agree otherwise in writing, either sUser or KraftHub may terminate the binding effect of these Terms of Use Agreement at any time, without explanation, upon written notice to the other. The User may provide a written notice of termination through the Site or Sites. In the event User properly terminates the binding effect of the Terms of Use, the User&rsquo;s right to use the Site or Sites and Site Services is automatically revoked, and the User&rsquo;s Account will be closed. As KraftHub is not a party to any Service Contract between Users, termination of this Agreement (or attempt to terminate this Agreement) does not terminate or otherwise impact any Service Contract or Project entered into between Users. If a User attempts to terminate the binding effect of these Terms of Use while having one or more pending Projects, Users agree (a) Users will continue to be bound by these Terms of Use until all such Projects have been closed on the Site or Sites; (b) KraftHub will continue to perform those Site Services necessary to complete any open Project or related transaction between Users; and (d) Users will continue to be obligated to pay any amounts accrued but unpaid as of the date of termination or as of the closure of any pending Service Contracts, whichever is later, to KraftHub for any Site Services or such other amounts owed under the Terms of Use and to any KraftHub Partners for any KraftHub Partner Services.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Without limiting KraftHub&rsquo;s other rights or remedies, KraftHub may temporarily or indefinitely revoke access to the Site or Sites or Site Services, deny User&rsquo;s registration, or permanently revoke User&rsquo;s access to the Site and refuse to provide any or all Site Services to users if: (i) Users breach any terms and conditions of this Terms of Use, (ii) KraftHub suspects or becomes aware that Users have provided false or misleading information to KraftHub, or (iii) KraftHub believes that User&rsquo;s actions may cause legal liability for other Users, KraftHub or its Affiliates, may be contrary to the interests of the Site or Sites or other Users, or may involve illicit or illegal activity. If a User&rsquo;s Account is temporarily or permanently closed, such User may not use the Site under the same Account or a different Account or re-register under a new Account without KraftHub&rsquo;s prior written consent. If a User attempts to use the Site under a different Account, KraftHub reserves the right to reclaim available funds in that Account and/or use an available Payment Method to pay for any amounts owed by a User to KraftHub to the extent permitted by applicable law.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Users acknowledge and agree that the value, reputation, and goodwill of the Site or Sites depend on the transparency of the User&rsquo;s Account status to all Users. Users therefore agree as follows: IF KRAFTHUB DECIDES TO TEMPORARILY OR PERMANENTLY CLOSE A USER&rsquo;S ACCOUNT, KRAFTHUB HAS THE RIGHT, WHERE ALLOWED BY LAW, TO: (A) NOTIFY OTHER USERS THAT HAVE ENTERED INTO SERVICE CONTRACTS WITH SUCH USER TO INFORM THEM OF THE USER&rsquo;S CLOSED ACCOUNT STATUS, (B) PROVIDE THOSE USERS WITH A SUMMARY OF THE REASONS FOR A USER&rsquo;S ACCOUNT CLOSURE. USERS AGREE THAT KRAFTHUB WILL HAVE NO LIABILITY ARISING FROM OR RELATING TO ANY NOTICE THAT IT MAY PROVIDE TO ANY USER REGARDING CLOSED ACCOUNT STATUS OR THE REASON(S) FOR THE CLOSURE.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">11.2 ACCOUNT DATA ON CLOSURE</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Except as otherwise required by law, if a User&rsquo;s Account is closed for any reason, a User will no longer have access to data, messages, files, or other materials a User keeps on the Site, and any closure of a User&rsquo;s Account may involve deletion of any content stored in such User&rsquo;s Account for which KraftHub will have no liability whatsoever. KraftHub, in its sole discretion and as permitted or required by law, may retain some or all of such User&rsquo;s Account information.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">11.3 DISPUTE RESOLUTION</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">Any dispute arising out of or in connection with these Terms of Use, including any question regarding its existence, validity, or termination, shall be referred to and finally resolved by arbitration in the Philippines in accordance with the Philippines arbitration rules. The language of the arbitration shall be English. The fees of the arbitrator shall be borne equally by the parties, provided that the arbitrator may require that such fees be borne in such other manner as the arbitrator determines is required in order for this arbitration clause to be enforceable under applicable law.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">11.4 SURVIVAL</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">After the termination of the Account of a User, the terms of these Terms of Use that expressly or by their nature contemplate performance after the binding effect of these Terms of Use terminates or expires will survive and continue in full force and effect. For example, the provisions requiring arbitration, permitting audits, protecting intellectual property, requiring non-bypass, indemnification, payment of fees, reimbursement, and setting forth limitations of liability each, by their nature, contemplate performance or observance after the termination of a User Account. Without limiting any other provisions of the Terms of Use, the termination of a User Account for any reason will not release a User or KraftHub from any obligations incurred prior to termination of a User Account or the binding effect of these Terms of Use or that thereafter may accrue in respect of any act or omission prior to such termination.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><br></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:17px;line-height:115%;">12. GENERAL</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><em><span style="font-size:15px;line-height:115%;">Section 13 discusses additional terms of the agreement between User and KraftHub.</span></em></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.1 ENTIRE AGREEMENT</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">This Agreement, together with the other Terms of Use, sets forth the entire agreement and understanding between User and KraftHub relating to the subject matter hereof and thereof and cancels and supersedes any prior or contemporaneous discussions, agreements, representations, warranties, and other communications between you and us, written or oral, to the extent they relate in any way to the subject matter hereof and thereof. The section headings in the Terms of Use are included for ease of reference only and have no binding effect. Even though KraftHub drafted the Terms of Use, Users represent that they had ample time to review and decide whether to agree to the Terms of Use. If an ambiguity or question of intent or interpretation of the Terms of Use arises, no presumption or burden of proof will arise favoring or disfavoring User or KraftHub because of the authorship of any provision of the Terms of Use.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.2 MODIFICATIONS; WAIVER</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">No modification or amendment to the Terms of Use will be binding upon KraftHub unless in a written instrument signed by a duly authorized representative of KraftHub or posted on the Site or Sites by KraftHub. KraftHub&rsquo;s failure to act with respect to a breach by a User does not waive KraftHub&rsquo;s right to act with respect to subsequent or similar breaches. KraftHub does not guarantee it will take action against all breaches of these Terms of Use.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.3 ASSIGNABILITY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">User may not assign the Terms of Use, or any of its rights or obligations hereunder, without KraftHub&rsquo;s prior written consent in the form of a written instrument signed by a duly authorized representative of KraftHub. KraftHub may freely assign this Agreement and the other Terms of Use without the User&rsquo;s consent. Any attempted assignment or transfer in violation of this subsection will be null and void. Subject to the foregoing restrictions, the Terms of Use are binding upon and will inure to the benefit of the successors, heirs, and permitted assigns of the parties.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.4 SEVERABILITY</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">If and to the extent any provision of these Terms of Use is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provisions or such portions thereof will be ineffective as to the jurisdiction in which they are illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability and will be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the parties. The illegality, invalidity, or unenforceability of such provision in that jurisdiction will not in any way affect the legality, validity, or enforceability of such provision in any other jurisdiction or any other provision in any jurisdiction.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.5 FORCE MAJEURE</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">KraftHub and the User will not be responsible for the failure to perform or any delay in performance of any obligation hereunder for a reasonable period due to labor disturbances, accidents, fires, floods, telecommunications or Internet failures, strikes, wars, riots, rebellions, blockades, acts of government, governmental requirements and regulations or restrictions imposed by law or any other similar conditions beyond the reasonable control of such party.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">12.6 GOVERNING LAW/CHOICE OF LAW</span></strong></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'><span style="font-size:15px;line-height:115%;">These Terms of Use shall be governed and interpreted pursuant to the laws of the Philippines.</span></p>
<p style='margin:0in;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;'>&nbsp;</p>
          
         <ToastContainer />
        </Form>
    </Wrapper>
  );
}

export default Terms;
